#!/usr/bin/env python3
import argparse
import csv
import json
import os
import random
import re
import shutil
from typing import Dict, List, Optional, Sequence, Tuple


IMG_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare anime character classification data from downloaded folders."
    )
    parser.add_argument(
        "--source-dir",
        type=str,
        default="downloads/characters_top10_each500_single_medium",
        help="Directory containing per-character folders.",
    )
    parser.add_argument(
        "--summary-file",
        type=str,
        default="downloads/characters_top10_each500_single_medium/summary.json",
        help="Optional summary json generated by crawler.",
    )
    parser.add_argument("--output-root", type=str, default="data")
    parser.add_argument("--image-dir", type=str, default="images")
    parser.add_argument("--meta-name", type=str, default="meta.csv")
    parser.add_argument("--label-map-name", type=str, default="label_map.json")
    parser.add_argument("--class-stats-name", type=str, default="class_stats.json")
    parser.add_argument("--head-box-name", type=str, default="head_boxes.json")
    parser.add_argument(
        "--link-mode",
        type=str,
        default="symlink",
        choices=["symlink", "hardlink", "copy", "none"],
        help="How to place image files under output root.",
    )
    parser.add_argument(
        "--anime-id",
        type=str,
        default="touhou_project",
        help="Default anime_id written to meta.csv",
    )
    parser.add_argument(
        "--style-id",
        type=str,
        default="pixiv_medium_nonai",
        help="Default style_id written to meta.csv",
    )
    parser.add_argument("--train-ratio", type=float, default=0.8)
    parser.add_argument("--val-ratio", type=float, default=0.1)
    parser.add_argument(
        "--no-val",
        action="store_true",
        help="Disable validation split and merge all non-train samples into test.",
    )
    parser.add_argument(
        "--max-per-class",
        type=int,
        default=None,
        help="Optional upper bound on images kept for each class (after sorting).",
    )
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def load_json_if_exists(path: str) -> Optional[dict]:
    if not path or not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, dict) else None


def parse_rank_from_name(name: str) -> Optional[int]:
    m = re.match(r"^(\d+)_", name)
    if m:
        return int(m.group(1))
    return None


def sanitize_dir_name(name: str) -> str:
    # Keep unicode characters while replacing path separators.
    return name.replace("/", "_").replace("\\", "_")


def list_image_files(folder: str) -> List[str]:
    files = []
    for name in os.listdir(folder):
        p = os.path.join(folder, name)
        if not os.path.isfile(p):
            continue
        if os.path.splitext(name)[1].lower() in IMG_EXTS:
            files.append(name)
    files.sort()
    return files


def materialize_file(src: str, dst: str, mode: str) -> None:
    if mode == "none":
        return
    ensure_dir(os.path.dirname(dst))

    if os.path.exists(dst):
        # Do not modify existing files to keep workspace safe.
        return

    if mode == "symlink":
        os.symlink(os.path.abspath(src), dst)
    elif mode == "hardlink":
        os.link(src, dst)
    elif mode == "copy":
        shutil.copy2(src, dst)
    else:
        raise ValueError(f"Unsupported link mode: {mode}")


def infer_items_from_summary(summary: dict) -> List[dict]:
    items = summary.get("items", [])
    if not isinstance(items, list):
        return []
    out = []
    for it in items:
        if not isinstance(it, dict):
            continue
        out.append(it)
    return out


def infer_items_from_folders(source_dir: str) -> List[dict]:
    items = []
    folders = [d for d in os.listdir(source_dir) if os.path.isdir(os.path.join(source_dir, d))]
    folders.sort()
    for folder in folders:
        rank = parse_rank_from_name(folder)
        if "_" in folder:
            name = folder.split("_", 1)[1]
        else:
            name = folder
        items.append(
            {
                "rank": rank if rank is not None else 999999,
                "name": name,
                "output_dir": os.path.join(source_dir, folder),
            }
        )
    return items


def compute_split_counts(n: int, train_ratio: float, val_ratio: float, no_val: bool) -> Tuple[int, int, int]:
    if no_val:
        train_n = int(n * train_ratio)
        test_n = n - train_n
        if n >= 2 and test_n == 0:
            test_n = 1
        train_n = n - test_n
        if train_n <= 0:
            train_n = max(1, n - 1)
            test_n = n - train_n
        return train_n, 0, test_n

    train_n = int(n * train_ratio)
    val_n = int(n * val_ratio)
    test_n = n - train_n - val_n

    if n >= 3:
        if val_n == 0:
            val_n = 1
        if test_n == 0:
            test_n = 1

    train_n = n - val_n - test_n
    if train_n <= 0:
        train_n = max(1, n - 2)
        remain = n - train_n
        val_n = remain // 2
        test_n = remain - val_n
    return train_n, val_n, test_n


def assign_splits(
    rows: List[dict],
    label_to_indices: Dict[int, List[int]],
    seed: int,
    train_ratio: float,
    val_ratio: float,
    no_val: bool,
) -> None:
    for label, indices in label_to_indices.items():
        rng = random.Random(seed + int(label))
        indices = indices[:]
        rng.shuffle(indices)
        n = len(indices)
        n_train, n_val, n_test = compute_split_counts(n, train_ratio, val_ratio, no_val=no_val)

        train_idx = indices[:n_train]
        val_idx = indices[n_train:n_train + n_val]
        test_idx = indices[n_train + n_val:n_train + n_val + n_test]

        for i in train_idx:
            rows[i]["split"] = "train"
        for i in val_idx:
            rows[i]["split"] = "val"
        for i in test_idx:
            rows[i]["split"] = "test"


def main() -> None:
    args = parse_args()
    if args.train_ratio <= 0 or args.train_ratio >= 1:
        raise ValueError("--train-ratio should be in (0, 1)")
    if args.no_val:
        args.val_ratio = 0.0
    else:
        if args.val_ratio < 0 or args.val_ratio >= 1:
            raise ValueError("--val-ratio should be in [0, 1)")
        if args.train_ratio + args.val_ratio >= 1:
            raise ValueError("--train-ratio + --val-ratio must be < 1")
    if args.max_per_class is not None and args.max_per_class <= 0:
        raise ValueError("--max-per-class must be positive when provided.")

    source_dir = os.path.abspath(args.source_dir)
    output_root = os.path.abspath(args.output_root)
    image_root = os.path.join(output_root, args.image_dir)

    ensure_dir(output_root)
    if args.link_mode != "none":
        ensure_dir(image_root)

    summary = load_json_if_exists(args.summary_file)
    if summary is not None:
        items = infer_items_from_summary(summary)
    else:
        items = infer_items_from_folders(source_dir)
    if not items:
        raise RuntimeError(f"No character folders found in {source_dir}")

    # Sort by rank for deterministic label ids.
    items.sort(key=lambda x: int(x.get("rank", 999999)))

    rows: List[dict] = []
    label_map: Dict[int, str] = {}
    class_counts: Dict[int, int] = {}
    label_to_indices: Dict[int, List[int]] = {}
    image_id = 1

    for label, item in enumerate(items):
        class_dir = item.get("output_dir")
        if not class_dir:
            continue
        class_dir = os.path.abspath(class_dir)
        if not os.path.isdir(class_dir):
            continue

        folder_name = os.path.basename(class_dir)
        class_meta_path = os.path.join(class_dir, "metadata.json")
        class_meta = load_json_if_exists(class_meta_path) or {}

        label_name = str(class_meta.get("name") or item.get("name") or folder_name)
        rank = int(class_meta.get("rank") or item.get("rank") or (label + 1))
        label_map[label] = label_name

        pixiv_item_map: Dict[str, dict] = {}
        for pitem in class_meta.get("items", []):
            if isinstance(pitem, dict) and "file" in pitem:
                pixiv_item_map[str(pitem["file"])] = pitem

        image_files = list(pixiv_item_map.keys()) if pixiv_item_map else list_image_files(class_dir)
        if not image_files:
            continue
        if args.max_per_class is not None:
            image_files = image_files[: args.max_per_class]

        class_subdir = f"{rank:02d}_{sanitize_dir_name(label_name)}"
        for image_name in image_files:
            src = os.path.join(class_dir, image_name)
            if not os.path.isfile(src):
                continue

            if args.link_mode == "none":
                file_path = os.path.abspath(src)
            else:
                rel_file_path = os.path.join(args.image_dir, class_subdir, image_name)
                dst = os.path.join(output_root, rel_file_path)
                materialize_file(src, dst, args.link_mode)
                file_path = rel_file_path

            pitem = pixiv_item_map.get(image_name, {})
            row = {
                "image_id": image_id,
                "file_path": file_path,
                "label": label,
                "label_name": label_name,
                "anime_id": args.anime_id,
                "style_id": args.style_id,
                "split": "train",  # placeholder; overwritten by assign_splits.
                "rank": rank,
                "source_dir": folder_name,
                "pixiv_id": pitem.get("id", ""),
                "pixiv_rank": pitem.get("rank", ""),
            }
            rows.append(row)
            idx = len(rows) - 1
            label_to_indices.setdefault(label, []).append(idx)
            class_counts[label] = class_counts.get(label, 0) + 1
            image_id += 1

    if not rows:
        raise RuntimeError("No valid images collected.")

    assign_splits(
        rows=rows,
        label_to_indices=label_to_indices,
        seed=args.seed,
        train_ratio=args.train_ratio,
        val_ratio=args.val_ratio,
        no_val=bool(args.no_val),
    )

    meta_path = os.path.join(output_root, args.meta_name)
    ensure_dir(os.path.dirname(meta_path))
    fieldnames = [
        "image_id",
        "file_path",
        "label",
        "label_name",
        "anime_id",
        "style_id",
        "split",
        "rank",
        "source_dir",
        "pixiv_id",
        "pixiv_rank",
    ]
    with open(meta_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    label_map_path = os.path.join(output_root, args.label_map_name)
    with open(label_map_path, "w", encoding="utf-8") as f:
        json.dump({str(k): v for k, v in label_map.items()}, f, ensure_ascii=False, indent=2)

    class_stats_path = os.path.join(output_root, args.class_stats_name)
    split_counts: Dict[str, int] = {"train": 0, "val": 0, "test": 0}
    for row in rows:
        split_counts[row["split"]] += 1
    stats_obj = {
        "num_images": len(rows),
        "num_classes": len(label_map),
        "split_counts": split_counts,
        "class_counts": {str(k): int(v) for k, v in class_counts.items()},
        "no_val": bool(args.no_val),
        "max_per_class": args.max_per_class,
    }
    with open(class_stats_path, "w", encoding="utf-8") as f:
        json.dump(stats_obj, f, ensure_ascii=False, indent=2)

    # Create an empty head box file for later detector outputs if absent.
    head_box_path = os.path.join(output_root, args.head_box_name)
    if not os.path.exists(head_box_path):
        with open(head_box_path, "w", encoding="utf-8") as f:
            json.dump({}, f, ensure_ascii=False, indent=2)

    print(f"[prepare_data] wrote: {meta_path}")
    print(f"[prepare_data] label map: {label_map_path}")
    print(f"[prepare_data] class stats: {class_stats_path}")
    print(
        f"[prepare_data] done, images={len(rows)}, classes={len(label_map)}, "
        f"split={split_counts}, link_mode={args.link_mode}"
    )


if __name__ == "__main__":
    main()
